apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/ashrene/gitops.git
    targetRevision: HEAD
    path: monitoring-gitops/grafana
    helm:
      chart: grafana
      repoURL: https://grafana.github.io/helm-charts
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true