apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 25.21.0
    helm:
      values: |
        server:
          additionalScrapeConfigs:
            - job_name: 'fastapi'
              metrics_path: /metrics
              static_configs:
                - targets: ['learn-application-test-app.learn.svc.cluster.local:80']

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
