apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/ashrene/gitops.git
    targetRevision: HEAD
    path: monitoring-gitops/prometheus
    helm:
      chart: prometheus
      repoURL: https://prometheus-community.github.io/helm-charts
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true